<?php
require_once '../includes/auth.php'; proteger_admin(); require_once '../includes/conexion.php'; require_once 'partials.php';
if (isset($_GET['eliminar'])) { $id=(int)$_GET['eliminar']; $conexion->query("DELETE FROM proyectos WHERE id=$id"); header('Location: proyectos.php'); exit; }
if ($_SERVER['REQUEST_METHOD']==='POST') {
  if (!empty($_POST['id'])) { $stmt=$conexion->prepare('UPDATE proyectos SET titulo=?, descripcion=?, imagen=?, demo_url=?, github_url=? WHERE id=?'); $stmt->bind_param('sssssi', $_POST['titulo'], $_POST['descripcion'], $_POST['imagen'], $_POST['demo_url'], $_POST['github_url'], $_POST['id']); }
  else { $stmt=$conexion->prepare('INSERT INTO proyectos (titulo, descripcion, imagen, demo_url, github_url) VALUES (?,?,?,?,?)'); $stmt->bind_param('sssss', $_POST['titulo'], $_POST['descripcion'], $_POST['imagen'], $_POST['demo_url'], $_POST['github_url']); }
  $stmt->execute(); header('Location: proyectos.php'); exit;
}
$edit = isset($_GET['editar']) ? $conexion->query('SELECT * FROM proyectos WHERE id='.(int)$_GET['editar'])->fetch_assoc() : null;
$items = $conexion->query('SELECT * FROM proyectos ORDER BY id DESC'); admin_header('Administrar Proyectos');
?>
<div class="row g-4"><div class="col-lg-4"><div class="card admin-card p-4"><h5><?= $edit?'Editar':'Agregar' ?> proyecto</h5><form method="POST"><input type="hidden" name="id" value="<?= $edit['id'] ?? '' ?>"><div class="mb-3"><input name="titulo" class="form-control bg-white text-dark" placeholder="Título" value="<?= htmlspecialchars($edit['titulo'] ?? '') ?>" required></div><div class="mb-3"><textarea name="descripcion" rows="4" class="form-control bg-white text-dark" placeholder="Descripción" required><?= htmlspecialchars($edit['descripcion'] ?? '') ?></textarea></div><div class="mb-3"><input name="imagen" class="form-control bg-white text-dark" value="<?= htmlspecialchars($edit['imagen'] ?? 'assets/img/project.svg') ?>" required></div><div class="mb-3"><input name="demo_url" class="form-control bg-white text-dark" placeholder="URL Demo" value="<?= htmlspecialchars($edit['demo_url'] ?? '#') ?>"></div><div class="mb-3"><input name="github_url" class="form-control bg-white text-dark" placeholder="URL GitHub" value="<?= htmlspecialchars($edit['github_url'] ?? '#') ?>"></div><button class="btn btn-primary w-100">Guardar</button></form></div></div><div class="col-lg-8"><div class="card admin-card p-4"><table class="table"><thead><tr><th>Título</th><th>Demo</th><th>GitHub</th><th>Acciones</th></tr></thead><tbody><?php while($r=$items->fetch_assoc()): ?><tr><td><?= htmlspecialchars($r['titulo']) ?></td><td><?= htmlspecialchars($r['demo_url']) ?></td><td><?= htmlspecialchars($r['github_url']) ?></td><td><a class="btn btn-sm btn-warning" href="?editar=<?= $r['id'] ?>">Editar</a> <a class="btn btn-sm btn-danger" onclick="return confirm('¿Eliminar?')" href="?eliminar=<?= $r['id'] ?>">Eliminar</a></td></tr><?php endwhile; ?></tbody></table></div></div></div>
<?php admin_footer(); ?>
